# Generated by Django 4.1.1 on 2022-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(default=11, max_length=1000),
            preserve_default=False,
        ),
    ]
